/* eslint-disable import/prefer-default-export */

export const links = {
  login: { url: '#', name: 'links.login' },
  account: { url: '#', name: 'links.account' },
  register: { url: '#', name: 'links.register' },
  arrivals: { url: '#', name: 'links.arrivals' },
  popular: { url: '#', name: 'links.popular' },
  top_pics: { url: '#', name: 'links.top_pics' },
  outlet: { url: '#', name: 'links.outlet' },
  support: { url: '#', name: 'links.support' },
  products: { url: '#', name: 'links.products' },
  delivery: { url: '#', name: 'links.delivery' },
  ship_delivery: { url: '#', name: 'links.ship_delivery' },
  return_policy: { url: '#', name: 'links.return_policy' },
  service_terms: { url: '#', name: 'links.service_terms' },
  privacy: { url: '#', name: 'links.privacy' },
  contacts: { url: '#', name: 'links.contacts' },
  legal: { url: '#', name: 'links.legal' },
  home: { url: '#', name: 'links.home' },
  about_us: { url: '#', name: 'links.about_us' },
  latest_news: { url: '#', name: 'links.latest_news' },
  reviews: { url: '#', name: 'links.reviews' },
  brands: { url: '#', name: 'links.brands' },
  sales: { url: '#', name: 'links.sales' },
  men: { url: '#', name: 'links.men' },
  women: { url: '#', name: 'links.women' },
  kids: { url: '#', name: 'links.kids' },
  baby: { url: '#', name: 'links.baby' },
  accessories: { url: '#', name: 'links.accessories' },
  youtube: { url: '#', name: 'links.youtube' },
  facebook: { url: '#', name: 'links.facebook' },
  pinterest: { url: '#', name: 'links.pinterest' },
  twitter: { url: '#', name: 'links.twitter' },
};
